server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
spring:
  application:
    name: apolloUser
  cloud:
    sentinel:
      transport:
       port: 8719
       dashboard: 127.0.0.1:7070